apiVersion: apps/v1
kind: Deployment
metadata:
  name: item-manager-backend
  namespace: item-manager
spec:
  replicas: 2
  selector:
    matchLabels:
      app: item-manager-backend
  template:
    metadata:
      labels:
        app: item-manager-backend
    spec:
      containers:
        - name: backend
          image: stanley80/item-manager-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: item-manager-config
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: item-manager-secret
                  key: POSTGRES_PASSWORD
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: item-manager-backend-service
  namespace: item-manager
  labels:
    app: item-manager-backend
spec:
  type: ClusterIP
  selector:
    app: item-manager-backend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
